name: 'Test'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Pages'
        uses: actions/configure-pages@v1
      - name: 'Setup Deno'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: 'Test'
        run: deno test --import-map=./import_map.json --allow-read=test/ test/
