name: "Test"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: "Check"
        run: deno task check
      - name: "Test"
        run: deno task test
      - name: "Build"
        run: deno task build
